workflows:
  ios-simulator-build:
    name: iOS Simulator Build (A.O.I. Native)
    environment:
      vars:
        XCODE_WORKSPACE: "App.xcworkspace"  # Standardname für Capacitor
        XCODE_SCHEME: "App"                 # Standardname für Capacitor
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npx cap sync ios
      - name: Build for iOS Simulator
        script: |
          cd ios/App
          pod install
          xcodebuild build \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            -configuration Debug \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO
    artifacts:
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
