workflows:
  ios-release:
    name: iOS Release (A.O.I. Native)
    environment:
      vars:
        BUNDLE_ID: "com.ekselvin.aoi"
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
        CM_APPLE_ID: "elsel.kevin@googlemail.com" # <-- hier deine Apple-ID eintragen
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
           npm install
           chmod +x node_modules/.bin/cap || true
           npx cap sync ios
      - name: CocoaPods install
        script: |
          cd ios/App
          pod install
      - name: Build iOS (Release)
        script: |
          cd ios/App
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            DEVELOPMENT_TEAM="$CM_TEAM_ID" \
            CODE_SIGN_STYLE=Automatic
    artifacts:
      - $CM_BUILD_DIR/App.xcarchive/Products/Applications/*.app

